# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/bce-core
    steps:
      - checkout
      - attach_workspace:
          at: ~/bce-core
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: packages/core/www
  deploy:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/bce-core
    steps:
      - add_ssh_keys:
          fingerprints:
            - '71:04:6d:98:7e:bd:e1:d0:af:8a:22:d4:e9:ed:12:4c'
      - checkout
      - attach_workspace:
          at: ~/bce-core
      - run: sed -i.bak 's/<head>/<head><base href="\/bce-core">/' packages/core/www/index.html
      - run: rm packages/core/www/index.html.bak
      - run: ./.circleci/gh-pages.sh

defaults: &defaults
  filters:
    branches:
      ignore:
        - gh-pages

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          <<: *defaults
      - deploy:
          <<: *defaults
          requires:
            - build
