# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
---
defaults: &defaults
  docker:
    - image: circleci/node:10-browsers
  working_directory: &working_dir ~/bce-core

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *working_dir
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm i
      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: packages/core/www
  gh-pages:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - '71:04:6d:98:7e:bd:e1:d0:af:8a:22:d4:e9:ed:12:4c'
      - checkout
      - attach_workspace:
          at: *working_dir
      - run: sed -i.bak 's/resources-url="/resources-url="\/bce-core/' packages/core/www/index.html
      - run: rm packages/core/www/index.html.bak
      - run: ./.circleci/gh-pages.sh

master: &master
  filters:
    branches:
      only:
        - master

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          <<: *master
      - gh-pages:
          <<: *master
          requires:
            - build
      - version:
          <<: *master
          requires:
            - build
